language: java
branches: 
  only:
    - source
env:
  secure: "fruRAPmWw94Koyh9K64L93jr7mWMDTBKVfqCpA+Qj169pa5W1XoChAsV7JYwAZJqpZNbplhr2Ux/1plLCu5Zq0ceWmYdfw9JnPH0Avw/pqSaPMMefNzFAyLgEXGcJx4I6R9mTF/axY2Oq2vXfqQjkqjio5iJi2f2epobRVGbrNc="
install: ./gradlew -b ci.gradle tasks
script: 
  - "./gradlew -b ci.gradle jbake --info --stacktrace"
  - "./gradlew -b ci.gradle publishGhPages --debug --stacktrace"
