<#-- Generated by scripts/disqus-archive.py from the Disqus export. Don't edit by hand. -->
<#noparse>
<details class="archived-comments">
  <summary>1 archived comment from the previous comment system (Disqus)</summary>
  <ol class="archived-comment-list">
    <li class="archived-comment" id="comment-1592173076">
      <p class="archived-comment-meta"><strong>Roberto Perez Alcolea</strong> &middot; <time datetime="2014-09-16T21:44:27Z">September 16, 2014</time></p>
      <div class="archived-comment-body"><p>What about "Refactoring: Improving the Design of Existing Code" by Martin Fowler? In my opinion, it can be a perfect fit in your list. Never heard about 'The Productive Programmer' I will take a look on it.</p></div>
    </li>
  </ol>
  <p class="archived-comment-note">These comments are kept here read-only. New comments go below.</p>
</details>
</#noparse>
