<#-- Generated by scripts/disqus-archive.py from the Disqus export. Don't edit by hand. -->
<#noparse>
<details class="archived-comments">
  <summary>5 archived comments from the previous comment system (Disqus)</summary>
  <ol class="archived-comment-list">
    <li class="archived-comment" id="comment-1460962784">
      <p class="archived-comment-meta"><strong>zen</strong> &middot; <time datetime="2014-06-30T01:07:24Z">June 30, 2014</time></p>
      <div class="archived-comment-body"><p>This is a great article, but the problem of culture is one that applies to any organisation.<br>'Devops in a box' as you say, would be attractive to many manager's who hear a buzzword and want to implement it to give themselves a nice update in their next &gt;=C level meeting.<br>Those slick salesmen are a danger to everyone!</p></div>
      <ol class="archived-comment-replies">
        <li class="archived-comment" id="comment-1460984660">
          <p class="archived-comment-meta"><strong>jmcgarr</strong> &middot; <time datetime="2014-06-30T01:31:45Z">June 30, 2014</time></p>
          <div class="archived-comment-body"><p>Totally agree.  You could change most of this article from 'agency' to 'corporation' and it would still apply.  I wanted this to read directly to those in government though.  Having a specific message helps make it more applicable.</p><p>Beware the slick salesmen!</p></div>
        </li>
      </ol>
    </li>
    <li class="archived-comment" id="comment-1462329946">
      <p class="archived-comment-meta"><strong>Matt Makai</strong> &middot; <time datetime="2014-06-30T21:15:45Z">June 30, 2014</time></p>
      <div class="archived-comment-body"><p>Damn Mike, you really nailed it with this one. Most of the "agile" implementations in government are Agile only for the specific team, then they have to map their activities to a larger waterfall model so management can digest the schedule.</p><p>A huge part of the cultural issue facing the government is that there are way too many non-technical managers and process people telling developers what to do. It's necessary, but not sufficient, to cut down the layers of non-technical management before a better technical environment will be possible in the Federal world.</p></div>
    </li>
    <li class="archived-comment" id="comment-1659646734">
      <p class="archived-comment-meta"><strong>Cliff</strong> &middot; <time datetime="2014-10-29T18:03:51Z">October 29, 2014</time></p>
      <div class="archived-comment-body"><p>Yes, great points.</p><p>What about organizations that outsource the operations too? Do you think that will be the trend? After all, gov data centers are hopeless behind in becoming cloud-like (i.e., having self-service provisioning). On the other hand, most gov data centers are operated by contractors - it would make little diff to just move to clouds like AWS. The big impediment with the gov data centers seems to be around the accounting of who uses what cloud services - i.e., the tracking to a user/account level is not there. Having each contract have its own AWS account solves that. Current gov data center contracts generally require provisioning to be requested and estimated and then done by data center personnel - i.e., not self service.</p><p>You are right, that going devops internally, an agency has to reorg to eliminate the silos. Some have been doing that (e.g., USCIS). I wonder what the future holds...</p></div>
      <ol class="archived-comment-replies">
        <li class="archived-comment" id="comment-1665059519">
          <p class="archived-comment-meta"><strong>jmcgarr</strong> &middot; <time datetime="2014-11-01T19:48:24Z">November 1, 2014</time></p>
          <div class="archived-comment-body"><p>Thanks Cliff for your comment!</p><p>Regarding government data centers, there is definitely a large hill to climb to get from current state to self service resources.  I would say this is also true of a lot of large enterprises as well.  It's not an easy problem to solve, but it's worth the effort.  And you don't have to go to cloud to improve how you use your internal resources.  Short of self-service provisioning, just getting better monitoring and insight into running servers could be easily achievable now and begin to build that bridge between dev and ops.</p><p>Regarding the elimination of silos, of course you should do that.  But it shouldn't stop you from pushing hard on the right changes.  Don't let silos stop...you may find that you can use them to your advantage.</p></div>
        </li>
      </ol>
    </li>
  </ol>
  <p class="archived-comment-note">These comments are kept here read-only. New comments go below.</p>
</details>
</#noparse>
