<#-- Generated by scripts/disqus-archive.py from the Disqus export. Don't edit by hand. -->
<#noparse>
<details class="archived-comments">
  <summary>1 archived comment from the previous comment system (Disqus)</summary>
  <ol class="archived-comment-list">
    <li class="archived-comment" id="comment-4991325936">
      <p class="archived-comment-meta"><strong>Ekeh Esom S.J.</strong> &middot; <time datetime="2020-07-14T11:16:42Z">July 14, 2020</time></p>
      <div class="archived-comment-body"><p>good article</p></div>
    </li>
  </ol>
  <p class="archived-comment-note">These comments are kept here read-only. New comments go below.</p>
</details>
</#noparse>
