<#-- Generated by scripts/disqus-archive.py from the Disqus export. Don't edit by hand. -->
<#noparse>
<details class="archived-comments">
  <summary>1 archived comment from the previous comment system (Disqus)</summary>
  <ol class="archived-comment-list">
    <li class="archived-comment" id="comment-4904494130">
      <p class="archived-comment-meta"><strong>Rancho</strong> &middot; <time datetime="2020-05-07T11:17:15Z">May 7, 2020</time></p>
      <div class="archived-comment-body"><p>I don't remember how I landed here, but reading this post was enjoyable.. I'm also discovering <a href="http://infoQ.com" rel="nofollow ugc noopener" target="_blank">infoQ.com</a> because of you now.. so, thanks! :)</p></div>
    </li>
  </ol>
  <p class="archived-comment-note">These comments are kept here read-only. New comments go below.</p>
</details>
</#noparse>
