<#-- Generated by scripts/disqus-archive.py from the Disqus export. Don't edit by hand. -->
<#noparse>
<details class="archived-comments">
  <summary>1 archived comment from the previous comment system (Disqus)</summary>
  <ol class="archived-comment-list">
    <li class="archived-comment" id="comment-4382281408">
      <p class="archived-comment-meta"><strong>Ryan Walls</strong> &middot; <time datetime="2019-03-17T13:31:06Z">March 17, 2019</time></p>
      <div class="archived-comment-body"><p>Good write up Mike!  I agree, good communication is key and roadmaps make the information easy to digest.</p></div>
    </li>
  </ol>
  <p class="archived-comment-note">These comments are kept here read-only. New comments go below.</p>
</details>
</#noparse>
