<#-- Generated by scripts/disqus-archive.py from the Disqus export. Don't edit by hand. -->
<#noparse>
<details class="archived-comments">
  <summary>2 archived comments from the previous comment system (Disqus)</summary>
  <ol class="archived-comment-list">
    <li class="archived-comment" id="comment-2758861371">
      <p class="archived-comment-meta"><strong>George Simpson</strong> &middot; <time datetime="2016-06-30T17:11:35Z">June 30, 2016</time></p>
      <div class="archived-comment-body"><p>That's right.</p></div>
    </li>
    <li class="archived-comment" id="comment-3949205464">
      <p class="archived-comment-meta"><strong>Nate Snapp</strong> &middot; <time datetime="2018-06-18T08:31:47Z">June 18, 2018</time></p>
      <div class="archived-comment-body"><p>The little cues are fascinating. I found a method a director used to give both a tone of respect, but also urgency and strength around senior engineers. Whenever they would bring a point that could not be argued, his assertion was always a louder than normal "Fine!". Sometimes this would happen to several points in succession. After doing this, there would often be a restatement, occasionally sprinkled with humor, followed by decision. It applied a firm pressure to limit winding conversations, assured the speaker that they were valued but not in charge, and arguments would lead to something, all while easing others to 'buy-in'. Worked well with his style.</p></div>
    </li>
  </ol>
  <p class="archived-comment-note">These comments are kept here read-only. New comments go below.</p>
</details>
</#noparse>
