<#-- Generated by scripts/disqus-archive.py from the Disqus export. Don't edit by hand. -->
<#noparse>
<details class="archived-comments">
  <summary>8 archived comments from the previous comment system (Disqus)</summary>
  <ol class="archived-comment-list">
    <li class="archived-comment" id="comment-1495474656">
      <p class="archived-comment-meta"><strong>krissputnam</strong> &middot; <time datetime="2014-07-21T13:28:47Z">July 21, 2014</time></p>
      <div class="archived-comment-body"><p>Awesome tips! I think the hardest thing for me to do is public speaking. Usually when I have a topic I'm passionate about, it's much easier than a boring presentation I've been tasked with by someone else.</p></div>
    </li>
    <li class="archived-comment" id="comment-1498149817">
      <p class="archived-comment-meta"><strong>yeahbutnobutyeahbut</strong> &middot; <time datetime="2014-07-22T16:39:30Z">July 22, 2014</time></p>
      <div class="archived-comment-body"><p><a href="http://stackoverflow.com" rel="nofollow ugc noopener" target="_blank">Stack Overflow</a> is another great way to highlight your expertise - asking a good question can be just as useful as providing answers.  Think about how many times you've searched for a solution to something you're stuck with and and a Stack Overflow answer has come up as the top result.</p></div>
      <ol class="archived-comment-replies">
        <li class="archived-comment" id="comment-1498660959">
          <p class="archived-comment-meta"><strong>jmcgarr</strong> &middot; <time datetime="2014-07-22T21:44:32Z">July 22, 2014</time></p>
          <div class="archived-comment-body"><p>I briefly considered adding StackOverflow to the list.  You are right, it is a great source of experts.  I should have definitely added it.  Thanks man!</p></div>
        </li>
      </ol>
    </li>
    <li class="archived-comment" id="comment-1498377127">
      <p class="archived-comment-meta"><strong>dan2bit</strong> &middot; <time datetime="2014-07-22T18:45:05Z">July 22, 2014</time></p>
      <div class="archived-comment-body"><p>Great list! One caution I'd throw out there on GitHub -&gt; Build in particular, that may apply more broadly to some folks: if you are currently employed, be sure your employee agreement allows you to open source your own work product, or at least doesn't automatically assign intellectual property rights to the employer for work you create while employed (which might include presentation materials as well, depending on the company or the agreement). I'm Not A Lawyer, and many companies couldn't care less about stuff like this, but you may want to ask your boss, co-workers, or HR/Legal department if you have a specific piece of code you want to make public, just so you don't create a situation where you need to look for a job prematurely or urgently.</p></div>
      <ol class="archived-comment-replies">
        <li class="archived-comment" id="comment-1498665160">
          <p class="archived-comment-meta"><strong>jmcgarr</strong> &middot; <time datetime="2014-07-22T21:47:35Z">July 22, 2014</time></p>
          <div class="archived-comment-body"><p>Good point Dan.</p><p>I would add that if your company doesn't currently open source software, then now is a good time to start.  Encourage them to start sharing their code.  If they do open source software, then you should contribute your project to their repo.  Open source code on Github under a company's repo can be just as valuable to the company as well as the individual contributors.</p></div>
        </li>
      </ol>
    </li>
    <li class="archived-comment" id="comment-2172541048">
      <p class="archived-comment-meta"><strong>Chris</strong> &middot; <time datetime="2015-08-03T20:32:40Z">August 3, 2015</time></p>
      <div class="archived-comment-body"><p>This is a great list.  How do I include a full-time job, you know, the actual work I do, in with all this?</p></div>
      <ol class="archived-comment-replies">
        <li class="archived-comment" id="comment-2172975682">
          <p class="archived-comment-meta"><strong>jmcgarr</strong> &middot; <time datetime="2015-08-04T01:54:27Z">August 4, 2015</time></p>
          <div class="archived-comment-body"><p>I would say that LinkedIN covers that use case, which is that of a traditional resume.</p></div>
        </li>
      </ol>
    </li>
    <li class="archived-comment" id="comment-2187201289">
      <p class="archived-comment-meta"><strong>Kate G</strong> &middot; <time datetime="2015-08-11T18:51:58Z">August 11, 2015</time></p>
      <div class="archived-comment-body"><p>Hi Mike! Kate with <a href="http://qz.com" rel="nofollow ugc noopener" target="_blank">qz.com</a> here. We really like this post and would love to talk about working with you. Please contact me via twitter or linkedin if you're interested.</p></div>
    </li>
  </ol>
  <p class="archived-comment-note">These comments are kept here read-only. New comments go below.</p>
</details>
</#noparse>
