<#-- Generated by scripts/disqus-archive.py from the Disqus export. Don't edit by hand. -->
<#noparse>
<details class="archived-comments">
  <summary>1 archived comment from the previous comment system (Disqus)</summary>
  <ol class="archived-comment-list">
    <li class="archived-comment" id="comment-2022508289">
      <p class="archived-comment-meta"><strong>Stephen Ritchie</strong> &middot; <time datetime="2015-05-13T15:51:46Z">May 13, 2015</time></p>
      <div class="archived-comment-body"><p>Mike, another *really* good article. I often have to struggle to influence a change in an organization's culture. These are some very helpful ways to analyze the situation. To pay it forward, I recently read "In Over Our Heads" by Robert Kegan and I'd recommend that book. Do you have any book recommendations?</p></div>
    </li>
  </ol>
  <p class="archived-comment-note">These comments are kept here read-only. New comments go below.</p>
</details>
</#noparse>
