<#-- Generated by scripts/disqus-archive.py from the Disqus export. Don't edit by hand. -->
<#noparse>
<details class="archived-comments">
  <summary>5 archived comments from the previous comment system (Disqus)</summary>
  <ol class="archived-comment-list">
    <li class="archived-comment" id="comment-3019684997">
      <p class="archived-comment-meta"><strong>jkaljundi</strong> &middot; <time datetime="2016-11-25T14:30:19Z">November 25, 2016</time></p>
      <div class="archived-comment-body"><p>Good stuff. While I'm biased towards our product, Weekdone, which does exactly weekly status updates (<a href="https://weekdone.com/)" rel="nofollow ugc noopener" target="_blank">https://weekdone.com/)</a> many things in regard to the process and value sounded the same we see many teams do.</p><p>The biggest complaint we hear from employees is that their leaders and managers don't share anything with them. Leaders want people to give status updates, but never do it themselves. It then rarely works. If leaders participate as almost equals the results are much better. Communication after all is 2-way.</p><p>Have you tried writing your daily updates into the doc right away? Wouldn't many people prefer that, as opposed to find time to read a 2-page doc? What we've seen is many people nowadays prefer smaller chunks of information in shorter intervals, and more gets read that way. Of course, it can be also more distracting.</p><p>Anyway thanks for showing a good example of other leaders!</p></div>
    </li>
    <li class="archived-comment" id="comment-3020016987">
      <p class="archived-comment-meta"><strong>Raf</strong> &middot; <time datetime="2016-11-25T17:52:40Z">November 25, 2016</time></p>
      <div class="archived-comment-body"><p>this is a very good idea thanks! I like the idea of one place to look at weekly notes as well and I bet it puts a pressure on meetings to have a useful output.</p></div>
    </li>
    <li class="archived-comment" id="comment-3022022929">
      <p class="archived-comment-meta"><strong>ldehai</strong> &middot; <time datetime="2016-11-27T02:02:34Z">November 27, 2016</time></p>
      <div class="archived-comment-body"><p>Thanks Mike. I like this method. I also hate meeting that waste so many time and no efficiency really.</p></div>
    </li>
    <li class="archived-comment" id="comment-3031133060">
      <p class="archived-comment-meta"><strong>Chaz</strong> &middot; <time datetime="2016-12-02T14:02:14Z">December 2, 2016</time></p>
      <div class="archived-comment-body"><p>I do my best remove as many meetings as possible in order to support development. Even slides and presentations I keep the details short and up front to encourage discuss and get people back to developing the product. I am going to implement this with my team as I have been looking for a better way to share information without overloading everyone.</p><p>I get concerned when employees say they do not understand what leadership is doing. They know we are busy but do not have a window into the details, hopefully this can provide that.</p></div>
    </li>
    <li class="archived-comment" id="comment-3065511191">
      <p class="archived-comment-meta"><strong>atxer</strong> &middot; <time datetime="2016-12-23T03:34:17Z">December 23, 2016</time></p>
      <div class="archived-comment-body"><p>Great article, Mike! Why not keep the WIR as a working document through the week and add your notes directly to this doc? On that Friday, you just have to keep the good parts and edit the rest away.</p></div>
    </li>
  </ol>
  <p class="archived-comment-note">These comments are kept here read-only. New comments go below.</p>
</details>
</#noparse>
