#!/usr/bin/env python3
"""Turn a Disqus export into read-only "archived comments" snippets for each post (revival task T045).

Usage: scripts/disqus-archive.py <disqus-export.xml[.gz]>

Writes src/jbake/templates/archived-comments/<post path without .html>.ftl, which post.ftl
includes when it exists. Only what was already public on Disqus is kept: the author's display
name, the date, and the comment text. Usernames, deleted comments, and spam are dropped. Comment
HTML is rebuilt from an allow-list (<p>, <br>, and http(s) links) and everything else is escaped.
The raw export is never committed.
"""
import collections, gzip, html, os, re, sys
import xml.etree.ElementTree as ET
from datetime import datetime
from html.parser import HTMLParser

NS = {"d": "http://disqus.com"}
DSQ_ID = "{http://disqus.com/disqus-internals}id"
SITE = re.compile(r"https?://(?:www\.)?mikemcgarr\.com/([^?#]*)")
OUT = "src/jbake/templates/archived-comments"
BUILT_CONTENT = "src/jbake/content"


class Sanitizer(HTMLParser):
    """Rebuild comment HTML from an allow-list: <p>, <br>, and http(s) links."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.out, self.open_a = [], 0

    def handle_starttag(self, tag, attrs):
        if tag == "p":
            self.out.append("<p>")
        elif tag == "br":
            self.out.append("<br>")
        elif tag == "a":
            href = dict(attrs).get("href") or ""
            if re.match(r"https?://", href):
                self.out.append(f'<a href="{html.escape(href, quote=True)}" rel="nofollow ugc noopener" target="_blank">')
                self.open_a += 1

    def handle_endtag(self, tag):
        if tag == "p":
            self.out.append("</p>")
        elif tag == "a" and self.open_a:
            self.out.append("</a>")
            self.open_a -= 1

    def handle_data(self, data):
        self.out.append(html.escape(data, quote=False))

    def result(self):
        return "".join(self.out) + "</a>" * self.open_a


def clean(message):
    s = Sanitizer()
    s.feed(message or "")
    s.close()
    body = s.result().strip()
    return body if body.startswith("<p>") else f"<p>{body}</p>"


def post_exists(path):
    base = os.path.join(BUILT_CONTENT, os.path.splitext(path)[0])
    return any(os.path.exists(base + ext) for ext in (".html", ".asciidoc", ".adoc", ".md"))


def render(comment, children, depth=0):
    when = datetime.strptime(comment["date"], "%Y-%m-%dT%H:%M:%SZ")
    pad = "  " * depth
    parts = [
        f'{pad}<li class="archived-comment" id="comment-{comment["id"]}">',
        f'{pad}  <p class="archived-comment-meta"><strong>{html.escape(comment["name"])}</strong> '
        f'&middot; <time datetime="{comment["date"]}">{when.strftime("%B %-d, %Y")}</time></p>',
        f'{pad}  <div class="archived-comment-body">{comment["body"]}</div>',
    ]
    kids = children.get(comment["id"], [])
    if kids:
        parts.append(f'{pad}  <ol class="archived-comment-replies">')
        parts += [render(k, children, depth + 2) for k in kids]
        parts.append(f"{pad}  </ol>")
    parts.append(f"{pad}</li>")
    return "\n".join(parts)


def main(path):
    raw = gzip.open(path).read() if path.endswith(".gz") else open(path, "rb").read()
    root = ET.fromstring(raw)
    threads = {t.get(DSQ_ID): t.findtext("d:link", namespaces=NS) for t in root.findall("d:thread", NS)}

    by_post = collections.defaultdict(list)
    for p in root.findall("d:post", NS):
        if p.findtext("d:isDeleted", namespaces=NS) == "true" or p.findtext("d:isSpam", namespaces=NS) == "true":
            continue
        m = SITE.match(threads.get(p.find("d:thread", NS).get(DSQ_ID)) or "")
        if not m or not post_exists(m.group(1)):
            print(f"skipped (no matching post): {threads.get(p.find('d:thread', NS).get(DSQ_ID))}", file=sys.stderr)
            continue
        parent = p.find("d:parent", NS)
        by_post[m.group(1)].append({
            "id": p.get(DSQ_ID),
            "parent": parent.get(DSQ_ID) if parent is not None else None,
            "name": (p.findtext("d:author/d:name", namespaces=NS) or "Anonymous").strip() or "Anonymous",
            "date": p.findtext("d:createdAt", namespaces=NS),
            "body": clean(p.findtext("d:message", namespaces=NS)),
        })

    for post, comments in sorted(by_post.items()):
        comments.sort(key=lambda c: c["date"])
        ids = {c["id"] for c in comments}
        children = collections.defaultdict(list)
        roots = []
        for c in comments:
            (children[c["parent"]] if c["parent"] in ids else roots).append(c)
        n = len(comments)
        snippet = "\n".join([
            "<#-- Generated by scripts/disqus-archive.py from the Disqus export. Don't edit by hand. -->",
            "<#noparse>",
            '<details class="archived-comments">',
            f'  <summary>{n} archived comment{"s" if n != 1 else ""} from the previous comment system (Disqus)</summary>',
            '  <ol class="archived-comment-list">',
            *[render(r, children, 2) for r in roots],
            "  </ol>",
            '  <p class="archived-comment-note">These comments are kept here read-only. New comments go below.</p>',
            "</details>",
            "</#noparse>",
            "",
        ])
        out = os.path.join(OUT, os.path.splitext(post)[0] + ".ftl")
        os.makedirs(os.path.dirname(out), exist_ok=True)
        with open(out, "w", encoding="utf-8") as f:
            f.write(snippet)
        print(f"{n:3} comments -> {out}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
